# Application Name
spring:
  application:
    name: oath-server
  jpa:
    show-sql: false
    generate-ddl: true
    mvc.favicon.enabled: false
    properties:
      hibernate:
        jdbc:
          batch_size: 5
#        ddl-auto: create
  # Properties for connection pool
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_test
    username: root
    password: Cristhian2018*Castillo
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  clientId: kentaurus
  client-secret: secret
  accessTokenValidititySeconds: 43200
  refreshTokenValiditySeconds: 2592000
